/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpractico2;

import javax.swing.JOptionPane;

/**
 *
 * @author Copito
 */
public class FormularioFinal extends javax.swing.JDialog {

    /**
     * Creates new form FormularioFinal
     */
    public FormularioFinal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        TextPrompt placeHolder= new TextPrompt("Nombre",jTFNombre);
        TextPrompt placeHolder2= new TextPrompt("Apellido",jTFApellido);
        TextPrompt placeHolder3= new TextPrompt("Telefono",jTFTelefono);
        
        jTFApellido.setEnabled(false);
        jTFNombre.setEnabled(false);
        jTFTelefono.setEnabled(false);
        jSpEdad.setEnabled(false);
        jCBsexo.setEnabled(false);
        
        jRBEnfermeria.setSelected(false);
        jRBFisioterapia.setSelected(false);
        jRBInformatica.setSelected(false);
        jRBNutricion.setSelected(false);
          
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jPCarreras = new javax.swing.JPanel();
        jRBEnfermeria = new javax.swing.JRadioButton();
        jRBNutricion = new javax.swing.JRadioButton();
        jRBFisioterapia = new javax.swing.JRadioButton();
        jRBInformatica = new javax.swing.JRadioButton();
        jPRegistrar = new javax.swing.JPanel();
        jLNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLApellido = new javax.swing.JLabel();
        jTFApellido = new javax.swing.JTextField();
        jLTelefono = new javax.swing.JLabel();
        jTFTelefono = new javax.swing.JTextField();
        jLEdad = new javax.swing.JLabel();
        jSpEdad = new javax.swing.JSpinner();
        jLSexo = new javax.swing.JLabel();
        jCBsexo = new javax.swing.JComboBox<>();
        jBInscribir = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jVaciar = new javax.swing.JButton();
        jPDetalleInscripcion = new javax.swing.JPanel();
        jCBAlumnosEnEnfermeria = new javax.swing.JComboBox<>();
        jCBAlumnosEnFisioterapia = new javax.swing.JComboBox<>();
        jSPNutricion = new javax.swing.JScrollPane();
        jLiNutricion = new javax.swing.JList<>();
        jSPInformatica = new javax.swing.JScrollPane();
        jLiInformatica = new javax.swing.JList<>();
        jPCantidades = new javax.swing.JPanel();
        jLCantEnEnfermeria = new javax.swing.JLabel();
        jTFEnferFemeninos = new javax.swing.JTextField();
        jTFEnferMasculinos = new javax.swing.JTextField();
        jLCantEnNutricion = new javax.swing.JLabel();
        jTFNutriFemeninos = new javax.swing.JTextField();
        jTFNutriMasculinos = new javax.swing.JTextField();
        jLCantEnFisioterapia = new javax.swing.JLabel();
        jTFFisioFemeninos = new javax.swing.JTextField();
        jTFFisioMasculinos = new javax.swing.JTextField();
        jLCantEnInformatica = new javax.swing.JLabel();
        jTFInforFemeninos = new javax.swing.JTextField();
        jTFInforMasculinos = new javax.swing.JTextField();
        jSTotal = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(230, 230, 230));

        Panel.setBackground(new java.awt.Color(240, 240, 240));

        jPCarreras.setBackground(new java.awt.Color(240, 240, 240));
        jPCarreras.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Carreras", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N
        jPCarreras.setForeground(new java.awt.Color(0, 0, 0));
        jPCarreras.setLayout(new java.awt.GridLayout(4, 1));

        jRBEnfermeria.setText("Lic. en Enfermeria");
        jRBEnfermeria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBEnfermeriaMouseClicked(evt);
            }
        });
        jPCarreras.add(jRBEnfermeria);

        jRBNutricion.setText("Lic. en Nutrición");
        jRBNutricion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBNutricionMouseClicked(evt);
            }
        });
        jPCarreras.add(jRBNutricion);

        jRBFisioterapia.setText("Lic. en Fisioterapia y Kinesiología");
        jRBFisioterapia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBFisioterapiaMouseClicked(evt);
            }
        });
        jPCarreras.add(jRBFisioterapia);

        jRBInformatica.setText("Lic. en Informática");
        jRBInformatica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBInformaticaMouseClicked(evt);
            }
        });
        jPCarreras.add(jRBInformatica);

        jPRegistrar.setBackground(new java.awt.Color(240, 240, 240));
        jPRegistrar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Registrar Alumnos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N

        jLNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLNombre.setText("Nombre: ");

        jTFNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFNombreFocusGained(evt);
            }
        });
        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });

        jLApellido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLApellido.setText("Apellido:");

        jLTelefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLTelefono.setText("Telefono:");

        jLEdad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLEdad.setText("Edad:");

        jSpEdad.setName(""); // NOI18N
        jSpEdad.setValue(18);

        jLSexo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLSexo.setText("Sexo:");

        jCBsexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCBsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "F", "M" }));

        javax.swing.GroupLayout jPRegistrarLayout = new javax.swing.GroupLayout(jPRegistrar);
        jPRegistrar.setLayout(jPRegistrarLayout);
        jPRegistrarLayout.setHorizontalGroup(
            jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistrarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFNombre)
                    .addComponent(jTFApellido)
                    .addComponent(jTFTelefono)
                    .addComponent(jSpEdad)
                    .addComponent(jCBsexo, 0, 373, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        jPRegistrarLayout.setVerticalGroup(
            jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellido)
                    .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTelefono)
                    .addComponent(jTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEdad)
                    .addComponent(jSpEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSexo)
                    .addComponent(jCBsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBInscribir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBInscribir.setText("Inscribir Alumno");
        jBInscribir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBInscribirMouseClicked(evt);
            }
        });

        jBLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBLimpiar.setText("Limpiar datos de Matriculación");

        jVaciar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jVaciar.setText("Vaciar Detalle de Inscripción");

        jPDetalleInscripcion.setBackground(new java.awt.Color(240, 240, 240));
        jPDetalleInscripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Detalle de Inscipción", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N

        jCBAlumnosEnEnfermeria.setBackground(new java.awt.Color(240, 240, 240));
        jCBAlumnosEnEnfermeria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCBAlumnosEnEnfermeria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBAlumnosEnEnfermeria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alumnos de Enfermeria", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N

        jCBAlumnosEnFisioterapia.setBackground(new java.awt.Color(240, 240, 240));
        jCBAlumnosEnFisioterapia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCBAlumnosEnFisioterapia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBAlumnosEnFisioterapia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alumnos de Fisioterapia", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N

        jLiNutricion.setBackground(new java.awt.Color(255, 255, 255));
        jLiNutricion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Alumnos de Nutrición", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N
        jLiNutricion.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jSPNutricion.setViewportView(jLiNutricion);

        jLiInformatica.setBackground(new java.awt.Color(255, 255, 255));
        jLiInformatica.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Alumnos de Informatica", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N
        jLiInformatica.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jSPInformatica.setViewportView(jLiInformatica);

        javax.swing.GroupLayout jPDetalleInscripcionLayout = new javax.swing.GroupLayout(jPDetalleInscripcion);
        jPDetalleInscripcion.setLayout(jPDetalleInscripcionLayout);
        jPDetalleInscripcionLayout.setHorizontalGroup(
            jPDetalleInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDetalleInscripcionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPDetalleInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCBAlumnosEnEnfermeria, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBAlumnosEnFisioterapia, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSPNutricion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jSPInformatica, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPDetalleInscripcionLayout.setVerticalGroup(
            jPDetalleInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDetalleInscripcionLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPDetalleInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPDetalleInscripcionLayout.createSequentialGroup()
                        .addComponent(jCBAlumnosEnEnfermeria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBAlumnosEnFisioterapia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPDetalleInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSPInformatica, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSPNutricion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPCantidades.setBackground(new java.awt.Color(240, 240, 240));
        jPCantidades.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cantidad de Alumnos por Carrera:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N
        jPCantidades.setForeground(new java.awt.Color(240, 240, 240));

        jLCantEnEnfermeria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLCantEnEnfermeria.setText("Enfermeria:");

        jTFEnferFemeninos.setEditable(false);
        jTFEnferFemeninos.setBackground(new java.awt.Color(240, 240, 240));
        jTFEnferFemeninos.setText("0");
        jTFEnferFemeninos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Femenino", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N
        jTFEnferFemeninos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEnferFemeninosActionPerformed(evt);
            }
        });

        jTFEnferMasculinos.setEditable(false);
        jTFEnferMasculinos.setBackground(new java.awt.Color(240, 240, 240));
        jTFEnferMasculinos.setText("0");
        jTFEnferMasculinos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Masculino", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N

        jLCantEnNutricion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLCantEnNutricion.setText("Nutrición:");

        jTFNutriFemeninos.setEditable(false);
        jTFNutriFemeninos.setBackground(new java.awt.Color(240, 240, 240));
        jTFNutriFemeninos.setText("0");
        jTFNutriFemeninos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Femenino", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N

        jTFNutriMasculinos.setEditable(false);
        jTFNutriMasculinos.setBackground(new java.awt.Color(240, 240, 240));
        jTFNutriMasculinos.setText("0");
        jTFNutriMasculinos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Masculino", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N

        jLCantEnFisioterapia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLCantEnFisioterapia.setText("Fisioterapia:");

        jTFFisioFemeninos.setEditable(false);
        jTFFisioFemeninos.setBackground(new java.awt.Color(240, 240, 240));
        jTFFisioFemeninos.setText("0");
        jTFFisioFemeninos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Femenino", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N
        jTFFisioFemeninos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFFisioFemeninosActionPerformed(evt);
            }
        });

        jTFFisioMasculinos.setEditable(false);
        jTFFisioMasculinos.setBackground(new java.awt.Color(240, 240, 240));
        jTFFisioMasculinos.setText("0");
        jTFFisioMasculinos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Masculino", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N
        jTFFisioMasculinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFFisioMasculinosActionPerformed(evt);
            }
        });

        jLCantEnInformatica.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLCantEnInformatica.setText("Informatica:");

        jTFInforFemeninos.setEditable(false);
        jTFInforFemeninos.setBackground(new java.awt.Color(240, 240, 240));
        jTFInforFemeninos.setText("0");
        jTFInforFemeninos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Femenino", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N
        jTFInforFemeninos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFInforFemeninosActionPerformed(evt);
            }
        });

        jTFInforMasculinos.setEditable(false);
        jTFInforMasculinos.setBackground(new java.awt.Color(240, 240, 240));
        jTFInforMasculinos.setText("0");
        jTFInforMasculinos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Masculino", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N
        jTFInforMasculinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFInforMasculinosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCantidadesLayout = new javax.swing.GroupLayout(jPCantidades);
        jPCantidades.setLayout(jPCantidadesLayout);
        jPCantidadesLayout.setHorizontalGroup(
            jPCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCantidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCantidadesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLCantEnEnfermeria)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLCantEnNutricion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFNutriFemeninos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEnferFemeninos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFEnferMasculinos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNutriMasculinos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134)
                .addGroup(jPCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPCantidadesLayout.createSequentialGroup()
                        .addComponent(jLCantEnInformatica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFInforFemeninos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPCantidadesLayout.createSequentialGroup()
                        .addComponent(jLCantEnFisioterapia)
                        .addGap(49, 49, 49)
                        .addComponent(jTFFisioFemeninos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFFisioMasculinos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFInforMasculinos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPCantidadesLayout.setVerticalGroup(
            jPCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCantidadesLayout.createSequentialGroup()
                .addGroup(jPCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCantidadesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFEnferMasculinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFEnferFemeninos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFFisioFemeninos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFFisioMasculinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPCantidadesLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLCantEnEnfermeria))
                    .addGroup(jPCantidadesLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLCantEnFisioterapia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCantidadesLayout.createSequentialGroup()
                        .addGroup(jPCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFNutriFemeninos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNutriMasculinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCantidadesLayout.createSequentialGroup()
                        .addComponent(jLCantEnNutricion)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCantidadesLayout.createSequentialGroup()
                        .addComponent(jLCantEnInformatica)
                        .addGap(35, 35, 35))
                    .addGroup(jPCantidadesLayout.createSequentialGroup()
                        .addGroup(jPCantidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFInforFemeninos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFInforMasculinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jSTotal.setBackground(new java.awt.Color(240, 240, 240));
        jSTotal.setForeground(new java.awt.Color(100, 100, 100));
        jSTotal.setMajorTickSpacing(10);
        jSTotal.setMinorTickSpacing(2);
        jSTotal.setPaintLabels(true);
        jSTotal.setPaintTicks(true);
        jSTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Total de alumnos Inscriptos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(100, 100, 100))); // NOI18N

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPCantidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPDetalleInscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPCarreras, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jBInscribir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(jBLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPCarreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBLimpiar))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jVaciar)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(jBInscribir)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPDetalleInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPCantidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jSTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFEnferFemeninosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEnferFemeninosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEnferFemeninosActionPerformed

    private void jTFFisioFemeninosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFFisioFemeninosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFFisioFemeninosActionPerformed

    private void jTFFisioMasculinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFFisioMasculinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFFisioMasculinosActionPerformed

    private void jTFInforFemeninosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFInforFemeninosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFInforFemeninosActionPerformed

    private void jTFInforMasculinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFInforMasculinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFInforMasculinosActionPerformed

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jRBEnfermeriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBEnfermeriaMouseClicked
        jRBEnfermeria.setSelected(true);
        jRBFisioterapia.setSelected(false);
        jRBInformatica.setSelected(false);
        jRBNutricion.setSelected(false);
        
        jTFApellido.setEnabled(true);
        jTFNombre.setEnabled(true);
        jTFTelefono.setEnabled(true);
        jSpEdad.setEnabled(true);
        jCBsexo.setEnabled(true);
        
        jTFNombre.requestFocus();
    }//GEN-LAST:event_jRBEnfermeriaMouseClicked

    private void jRBNutricionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBNutricionMouseClicked
        // TODO add your handling code here:
        jRBEnfermeria.setSelected(false);
        jRBFisioterapia.setSelected(false);
        jRBInformatica.setSelected(false);
        jRBNutricion.setSelected(true);
        
        jTFApellido.setEnabled(true);
        jTFNombre.setEnabled(true);
        jTFTelefono.setEnabled(true);
        jSpEdad.setEnabled(true);
        jCBsexo.setEnabled(true);
        
        jTFNombre.requestFocus();
    }//GEN-LAST:event_jRBNutricionMouseClicked

    private void jRBFisioterapiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBFisioterapiaMouseClicked
        // TODO add your handling code here:
        jRBEnfermeria.setSelected(false);
        jRBFisioterapia.setSelected(true);
        jRBInformatica.setSelected(false);
        jRBNutricion.setSelected(false);
        
        jTFApellido.setEnabled(true);
        jTFNombre.setEnabled(true);
        jTFTelefono.setEnabled(true);
        jSpEdad.setEnabled(true);
        jCBsexo.setEnabled(true);
        
        jTFNombre.requestFocus();
    }//GEN-LAST:event_jRBFisioterapiaMouseClicked

    private void jRBInformaticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBInformaticaMouseClicked
        // TODO add your handling code here:
        jRBEnfermeria.setSelected(false);
        jRBFisioterapia.setSelected(false);
        jRBInformatica.setSelected(true);
        jRBNutricion.setSelected(false);
        
        jTFApellido.setEnabled(true);
        jTFNombre.setEnabled(true);
        jTFTelefono.setEnabled(true);
        jSpEdad.setEnabled(true);
        jCBsexo.setEnabled(true);   
        
        jTFNombre.requestFocus();
    }//GEN-LAST:event_jRBInformaticaMouseClicked

    private void jTFNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNombreFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreFocusGained

    private void jBInscribirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBInscribirMouseClicked
        // TODO add your handling code here:
        nombre=jTFNombre.getText();
        apellido=jTFApellido.getText();
        telefono=jTFTelefono.getText();
        edad=(int) jSpEdad.getValue();
        sexo=jCBsexo.getSelectedItem().toString();
        
        if(nombre.isEmpty()){
            JOptionPane.showMessageDialog(this,"El campo NOMBRE no puede quedar vacio","Error!",JOptionPane.ERROR_MESSAGE);
            
            jTFApellido.setText("");
            jTFNombre.setText("");
            jTFTelefono.setText("");
            jSpEdad.setValue(18);
            jCBsexo.setSelectedIndex(0);

            jTFApellido.setEnabled(false);
            jTFNombre.setEnabled(false);
            jTFTelefono.setEnabled(false);
            jSpEdad.setEnabled(false);
            jCBsexo.setEnabled(false);

            jRBEnfermeria.setSelected(false);
            jRBFisioterapia.setSelected(false);
            jRBInformatica.setSelected(false);
            jRBNutricion.setSelected(false);
            
        }else if(apellido.isEmpty()){
            JOptionPane.showMessageDialog(this,"El campo APELLIDO no puede quedar vacio","Error!",JOptionPane.ERROR_MESSAGE);
            
            jTFApellido.setText("");
            jTFNombre.setText("");
            jTFTelefono.setText("");
            jSpEdad.setValue(18);
            jCBsexo.setSelectedIndex(0);
            
            jTFApellido.setEnabled(false);
            jTFNombre.setEnabled(false);
            jTFTelefono.setEnabled(false);
            jSpEdad.setEnabled(false);
            jCBsexo.setEnabled(false);

            jRBEnfermeria.setSelected(false);
            jRBFisioterapia.setSelected(false);
            jRBInformatica.setSelected(false);
            jRBNutricion.setSelected(false);
        }else if(edad<=18){
            JOptionPane.showMessageDialog(this,"La edad no puede ser menor a 18","Error!",JOptionPane.ERROR_MESSAGE);
            
            jTFApellido.setText("");
            jTFNombre.setText("");
            jTFTelefono.setText("");
            jSpEdad.setValue(18);
            jCBsexo.setSelectedIndex(0);
            
            jTFApellido.setEnabled(false);
            jTFNombre.setEnabled(false);
            jTFTelefono.setEnabled(false);
            jSpEdad.setEnabled(false);
            jCBsexo.setEnabled(false);

            jRBEnfermeria.setSelected(false);
            jRBFisioterapia.setSelected(false);
            jRBInformatica.setSelected(false);
            jRBNutricion.setSelected(false);
        }else if(sexo.equals("Seleccione...")){
            JOptionPane.showMessageDialog(this,"No ha seleccionado sexo","Error!",JOptionPane.ERROR_MESSAGE);
            
            jTFApellido.setText("");
            jTFNombre.setText("");
            jTFTelefono.setText("");
            jSpEdad.setValue(18);
            jCBsexo.setSelectedIndex(0);
            
            jTFApellido.setEnabled(false);
            jTFNombre.setEnabled(false);
            jTFTelefono.setEnabled(false);
            jSpEdad.setEnabled(false);
            jCBsexo.setEnabled(false);

            jRBEnfermeria.setSelected(false);
            jRBFisioterapia.setSelected(false);
            jRBInformatica.setSelected(false);
            jRBNutricion.setSelected(false);
        }else{
            aux=nombre+" "+apellido+telefono+" "+edad+" "+sexo;
        }
    }//GEN-LAST:event_jBInscribirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioFinal dialog = new FormularioFinal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private String nombre;
    private String apellido;
    private String telefono;
    private int edad;
    private String sexo;
    private String aux;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton jBInscribir;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JComboBox<String> jCBAlumnosEnEnfermeria;
    private javax.swing.JComboBox<String> jCBAlumnosEnFisioterapia;
    private javax.swing.JComboBox<String> jCBsexo;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLCantEnEnfermeria;
    private javax.swing.JLabel jLCantEnFisioterapia;
    private javax.swing.JLabel jLCantEnInformatica;
    private javax.swing.JLabel jLCantEnNutricion;
    private javax.swing.JLabel jLEdad;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLSexo;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JList<String> jLiInformatica;
    private javax.swing.JList<String> jLiNutricion;
    private javax.swing.JPanel jPCantidades;
    private javax.swing.JPanel jPCarreras;
    private javax.swing.JPanel jPDetalleInscripcion;
    private javax.swing.JPanel jPRegistrar;
    private javax.swing.JRadioButton jRBEnfermeria;
    private javax.swing.JRadioButton jRBFisioterapia;
    private javax.swing.JRadioButton jRBInformatica;
    private javax.swing.JRadioButton jRBNutricion;
    private javax.swing.JScrollPane jSPInformatica;
    private javax.swing.JScrollPane jSPNutricion;
    private javax.swing.JSlider jSTotal;
    private javax.swing.JSpinner jSpEdad;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFEnferFemeninos;
    private javax.swing.JTextField jTFEnferMasculinos;
    private javax.swing.JTextField jTFFisioFemeninos;
    private javax.swing.JTextField jTFFisioMasculinos;
    private javax.swing.JTextField jTFInforFemeninos;
    private javax.swing.JTextField jTFInforMasculinos;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNutriFemeninos;
    private javax.swing.JTextField jTFNutriMasculinos;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JButton jVaciar;
    // End of variables declaration//GEN-END:variables
}
